export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const LOAD_EXERCISES_SUCCCESS = 'LOAD_EXERCISES_SUCCCESS';
export const LOAD_WORKOUTS_ARCHIVE_SUCCESS = 'LOAD_WORKOUTS_ARCHIVE_SUCCESS';
export const ADD_BLOCK_TO_WORKOUT = 'ADD_BLOCK_TO_WORKOUT';
export const ADD_EXERCISE_TO_BLOCK = 'ADD_EXERCISE_TO_BLOCK';
export const CREATE_WORKOUT_SUCCESS = 'CREATE_WORKOUT_SUCCESS';
export const UPDATE_WORKOUT_SUCCESS = 'UPDATE_WORKOUT_SUCCESS';
